import React from 'react'
import Head from 'next/head'
import Machinery from '../components/Machinery/Machinery'


const machinery = () => {
  return (
    // <>
    // <Head>
    //     <title>Machinery</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

      <div className='mt-[80px]'>
       <Machinery />
      </div>
    
    // </>
     
  )
}

export default machinery