import React from 'react'
import Head from 'next/head'
import Services from '../components/Services/Services'

const products = () => {
  return (
    // <>
    // <Head>
    //     <title>Products</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
       
    //   </Head>
      <div className='px-[5%] mt-5 md:mt-20'>
        <Services />
     </div>
    // </>
    
  )
}

export default products